# Generated by Django 4.2.23 on 2025-07-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_trabajador', models.CharField(max_length=20)),
                ('nombre_trabajador', models.CharField(max_length=100)),
                ('epp_solicitado', models.TextField()),
                ('personal_bodega', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pdf_generado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'autorizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'epp',
                'ordering': ['nombre'],
            },
        ),
    ]
