# Generated by Django 4.2.23 on 2025-07-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0004_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacion',
            name='documento_firmado',
            field=models.FileField(blank=True, null=True, upload_to='autorizaciones_pdf/completadas/'),
        ),
        migrations.AddField(
            model_name='autorizacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='faena',
            field=models.CharField(choices=[('mantos_cobrizos', 'Mantos cobrizos'), ('tigresa', 'Tigresa'), ('revoltosa', 'Revoltosa')], default='mantos_blancos', max_length=20),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='pdf_generado',
            field=models.FileField(blank=True, null=True, upload_to='autorizaciones_pdf/pendientes/'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='faena',
            field=models.CharField(blank=True, choices=[('mantos_cobrizos', 'Mantos cobrizos'), ('tigresa', 'Tigresa'), ('revoltosa', 'Revoltosa')], max_length=20, null=True),
        ),
    ]
