# Generated by Django 4.2.23 on 2025-07-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='faena',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('bodega', 'Bodega'), ('prevencion', 'Prevención')], default='bodega', max_length=20),
        ),
    ]
