# Generated by Django 4.2.23 on 2025-07-26 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_customuser_faena_alter_customuser_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariobodega',
            options={},
        ),
    ]
