# Generated by Django 4.2.23 on 2025-07-24 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autorizacion',
            options={},
        ),
    ]
