# Generated by Django 4.2.23 on 2025-07-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0002_alter_autorizacion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacion',
            name='faena',
            field=models.CharField(choices=[('mantos_blancos', 'Mantos Blancos'), ('tigresa', 'Tigresa'), ('revoltosa', 'Revoltosa')], default='mantos_blancos', max_length=20),
        ),
    ]
